// Agape design tokens — shared with the website.
export const C = {
  ink: "#0F0B12",
  ink2: "#17111D",
  ink3: "#221A2A",
  cream: "#F4EEE4",
  paper: "#FBF8F3",
  white: "#FFFFFF",
  flame: "#FF5A1F",
  brand: "#FF5A1F",
  brandDeep: "#D9430F",
  sun: "#FFC23D",
  gold: "#FFC23D",
  rose: "#FF3D7F",
  violet: "#6E4BFF",
  mint: "#2ED3A0",
  sky: "#4CC3FF",
  muted: "rgba(15,11,18,0.58)",
  faint: "rgba(15,11,18,0.08)",
  creamMuted: "rgba(244,238,228,0.62)",
  lilac: "#EFE9FF",
  peach: "#FFE3D6",
  mintSoft: "#D5F5E8",
  sunSoft: "#FFF0B8",
  skySoft: "#DDF1FF",
  roseSoft: "#FFE0EC",
  deepViolet: "#1D1233",
};

export const F = {
  display: "Bricolage-ExtraBoldCondensed",
  displayBold: "Bricolage-Bold",
  displaySemi: "Bricolage-SemiBold",
  serif: "InstrumentSerif-Regular",
  serifItalic: "InstrumentSerif-Italic",
  sans: "Geist-Regular",
  sansMedium: "Geist-Medium",
  sansSemi: "Geist-SemiBold",
  sansBold: "Geist-Bold",
  mono: "GeistMono-Medium",
};

export const R = { sm: 14, md: 22, lg: 28, xl: 36, pill: 999 };

export const fontMap = {
  [F.display]: require("../assets/fonts/Bricolage-ExtraBoldCondensed.ttf"),
  [F.displayBold]: require("../assets/fonts/Bricolage-Bold.ttf"),
  [F.displaySemi]: require("../assets/fonts/Bricolage-SemiBold.ttf"),
  [F.serif]: require("../assets/fonts/InstrumentSerif-Regular.ttf"),
  [F.serifItalic]: require("../assets/fonts/InstrumentSerif-Italic.ttf"),
  [F.sans]: require("../assets/fonts/Geist-Regular.ttf"),
  [F.sansMedium]: require("../assets/fonts/Geist-Medium.ttf"),
  [F.sansSemi]: require("../assets/fonts/Geist-SemiBold.ttf"),
  [F.sansBold]: require("../assets/fonts/Geist-Bold.ttf"),
  [F.mono]: require("../assets/fonts/GeistMono-Medium.ttf"),
};

export const IMG = {
  worshipPink: require("../assets/images/worship-pink.jpg"),
  worshipTeal: require("../assets/images/worship-teal.jpg"),
  worshipOrange: require("../assets/images/worship-orange.jpg"),
  threeFriends: require("../assets/images/three-friends.jpg"),
  bibleCoffee: require("../assets/images/bible-coffee.jpg"),
  bricks: require("../assets/images/bricks.jpg"),
  campfire: require("../assets/images/campfire.jpg"),
  phoneHand: require("../assets/images/phone-hand.jpg"),
  mugBible: require("../assets/images/mug-bible.jpg"),
  crossMountain: require("../assets/images/cross-mountain.jpg"),
  womanForest: require("../assets/images/woman-forest.jpg"),
  cityNight: require("../assets/images/city-night.jpg"),
  handSunset: require("../assets/images/hand-sunset.jpg"),
  dove: require("../assets/images/dove.jpg"),
  mountainPeaks: require("../assets/images/mountain-peaks.jpg"),
  openArms: require("../assets/images/mountain-open-arms.jpg"),
  alps: require("../assets/images/alps.jpg"),
  handsTogether: require("../assets/images/hands-together.jpg"),
  womenLaughing: require("../assets/images/women-laughing.jpg"),
  manReading: require("../assets/images/man-reading.jpg"),
  kidsPlay: require("../assets/images/kids-play.jpg"),
  microphone: require("../assets/images/microphone.jpg"),
  teamMeeting: require("../assets/images/team-meeting.jpg"),
  friendsTeal: require("../assets/images/friends-teal.jpg"),
  candleHands: require("../assets/images/candle-hands.jpg"),
  crossDusk: require("../assets/images/cross-dusk.jpg"),
  womanPraying: require("../assets/images/woman-praying.jpg"),
  concertLights: require("../assets/images/concert-lights.jpg"),
  neonCross: require("../assets/images/neon-cross.jpg"),
  bibleDark: require("../assets/images/bible-dark.jpg"),
  sunrise: require("../assets/images/sunrise-silhouettes.jpg"),
  girlPraying: require("../assets/images/girl-praying-light.jpg"),
  handsStack: require("../assets/images/hands-stack.jpg"),
  chapel: require("../assets/images/white-chapel.jpg"),
  // Agape International Ministries — real photos
  homeWorship: require("../assets/images/agape-home-worship.jpg"),
  familyDay: require("../assets/images/agape-family-day.jpg"),
  squadBand: require("../assets/images/agape-squad-band.jpg"),
  squadHealer: require("../assets/images/agape-squad-healer.jpg"),
  families: require("../assets/images/agape-families.jpg"),
  institute: require("../assets/images/agape-institute.jpg"),
  kidsHearts: require("../assets/images/agape-kids-hearts.jpg"),
  kidsChurch: require("../assets/images/agape-kids-church.jpg"),
  prayerWorship: require("../assets/images/agape-prayer-worship.jpg"),
  logoMark: require("../assets/images/logo-mark.png"),
  logoMarkLight: require("../assets/images/logo-mark-light.png"),
  logoFull: require("../assets/images/logo-full.png"),
};

export const shadow = (y = 18, blur = 30, opacity = 0.18, color = "#1a0a14") => ({
  shadowColor: color,
  shadowOffset: { width: 0, height: y },
  shadowOpacity: opacity,
  shadowRadius: blur,
  elevation: Math.round(y / 2),
});
