#!/bin/sh
# Builds setup.sql = every migration + the starter games, in order, for pasting into
# Supabase → SQL Editor on a brand-new project. Run after adding a migration.
cd "$(dirname "$0")"
{
  echo "-- GENERATED by make-setup.sh — do not edit. Paste into Supabase → SQL Editor → Run (new project only)."
  for f in migrations/*.sql seed.sql; do echo; echo "-- ===== $f"; cat "$f"; done
} > setup.sql
echo "wrote backend/supabase/setup.sql"
