-- GENERATED by make-setup.sh — do not edit. Paste into Supabase → SQL Editor → Run (new project only).

-- ===== migrations/20260101000000_initial_schema.sql
-- =====================================================================
-- AGAPE INTERNATIONAL — Supabase schema (Postgres + RLS + Realtime)
-- Run in the Supabase SQL editor, or save as a migration.
-- Mirrors the data model in the proposal: users, courses→modules→lessons,
-- videos/documents, messaging, rides (+ live location log), games,
-- events, giving and notifications.
-- =====================================================================

create extension if not exists "pgcrypto";

-- ---------- Users & roles --------------------------------------------
create type public.user_role as enum ('member', 'volunteer', 'staff', 'admin');

create table public.profiles (
  id uuid primary key references auth.users on delete cascade,
  full_name text,
  avatar_url text,
  phone text,
  role public.user_role not null default 'member',
  language text not null default 'en',
  kids_mode boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.is_staff() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role in ('staff','admin'));
$$;

create or replace function public.my_role() returns public.user_role
language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_volunteer() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role in ('volunteer','staff','admin'));
$$;

-- create a profile automatically on sign-up
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email), new.raw_user_meta_data->>'avatar_url');
  return new;
end $$;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- Ministries / small groups --------------------------------
create table public.ministries (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  color text,
  meets text,
  cover_url text,
  created_at timestamptz not null default now()
);
create table public.ministry_members (
  ministry_id uuid references public.ministries on delete cascade,
  user_id uuid references public.profiles on delete cascade,
  is_leader boolean not null default false,
  joined_at timestamptz not null default now(),
  primary key (ministry_id, user_id)
);

-- ---------- Content: series, videos, documents -----------------------
create table public.series (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  book text,                       -- organise by book of the Bible…
  topic text,                      -- …or by topic
  cover_url text,
  created_at timestamptz not null default now()
);
create table public.videos (
  id uuid primary key default gen_random_uuid(),
  series_id uuid references public.series on delete set null,
  title text not null,
  speaker text,
  description text,
  stream_uid text,                 -- Cloudflare Stream / Mux playback id
  youtube_id text,                 -- or embedded YouTube (live)
  duration_sec int,
  is_live boolean not null default false,
  views int not null default 0,
  published_at timestamptz default now()
);
create table public.documents (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  r2_key text not null,            -- object key in Cloudflare R2
  pages int,
  created_at timestamptz not null default now()
);

-- ---------- Courses → modules → lessons ------------------------------
create table public.courses (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  category text,
  cover_url text,
  published boolean not null default false,
  created_at timestamptz not null default now()
);
create table public.modules (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses on delete cascade,
  title text not null,
  position int not null default 0
);
create type public.lesson_kind as enum ('video', 'pdf', 'quiz');
create table public.lessons (
  id uuid primary key default gen_random_uuid(),
  module_id uuid not null references public.modules on delete cascade,
  title text not null,
  kind public.lesson_kind not null,
  video_id uuid references public.videos on delete set null,
  document_id uuid references public.documents on delete set null,
  quiz jsonb,                      -- [{prompt, options[], answer}]
  minutes int,
  position int not null default 0
);
create table public.lesson_progress (
  user_id uuid not null default auth.uid() references public.profiles on delete cascade,
  lesson_id uuid not null references public.lessons on delete cascade,
  completed_at timestamptz not null default now(),
  primary key (user_id, lesson_id)
);
create table public.sermon_notes (
  user_id uuid not null default auth.uid() references public.profiles on delete cascade,
  video_id uuid not null references public.videos on delete cascade,
  body text not null default '',
  updated_at timestamptz not null default now(),
  primary key (user_id, video_id)
);

-- ---------- Messaging -----------------------------------------------
create type public.conversation_kind as enum ('direct', 'group', 'announcement');
create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  kind public.conversation_kind not null,
  name text,
  ministry_id uuid references public.ministries on delete set null,
  created_at timestamptz not null default now()
);
create table public.conversation_members (
  conversation_id uuid references public.conversations on delete cascade,
  user_id uuid references public.profiles on delete cascade,
  last_read_at timestamptz,
  primary key (conversation_id, user_id)
);
create table public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations on delete cascade,
  sender_id uuid not null default auth.uid() references public.profiles on delete cascade,
  body text not null check (char_length(body) <= 4000),
  created_at timestamptz not null default now()
);
create index on public.messages (conversation_id, created_at desc);

-- ---------- Prayer wall ---------------------------------------------
create table public.prayer_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references public.profiles on delete cascade,
  body text not null check (char_length(body) <= 500),
  anonymous boolean not null default false,
  pray_count int not null default 0,
  answered boolean not null default false,
  hidden boolean not null default false,  -- moderation
  created_at timestamptz not null default now()
);
create table public.prayer_reactions (
  request_id uuid references public.prayer_requests on delete cascade,
  user_id uuid default auth.uid() references public.profiles on delete cascade,
  created_at timestamptz not null default now(),
  primary key (request_id, user_id)
);
-- public view that never exposes who posted an anonymous request
create view public.prayer_wall with (security_invoker = true) as
  select r.id, r.body, r.anonymous, r.pray_count, r.answered, r.created_at,
         case when r.anonymous then null else p.full_name end as author_name
  from public.prayer_requests r left join public.profiles p on p.id = r.user_id
  where not r.hidden;

create or replace function public.pray_for(request_id uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  insert into public.prayer_reactions (request_id, user_id) values (pray_for.request_id, auth.uid())
  on conflict do nothing;
  if found then
    update public.prayer_requests set pray_count = pray_count + 1 where id = pray_for.request_id;
  end if;
end $$;

-- confidential pastoral care (staff-only visibility)
create table public.care_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references public.profiles on delete cascade,
  kind text not null default 'visit',     -- visit | counselling | other
  details text,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

-- ---------- Bible games ---------------------------------------------
create type public.game_kind as enum ('trivia', 'verse_match');
create table public.question_packs (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  game public.game_kind not null,
  published boolean not null default false,
  created_at timestamptz not null default now()
);
create table public.questions (
  id uuid primary key default gen_random_uuid(),
  pack_id uuid not null references public.question_packs on delete cascade,
  prompt text not null,            -- trivia question, or verse with ___ blanks
  options jsonb not null,          -- ["Moses","Noah",…]
  answer jsonb not null,           -- 1  or  ["world","Son"]
  reference text                   -- "John 3:16"
);
create table public.game_scores (
  id bigint generated always as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles on delete cascade,
  game public.game_kind not null,
  points int not null check (points between 0 and 1000),
  created_at timestamptz not null default now()
);
create view public.leaderboard_weekly with (security_invoker = true) as
  select s.user_id, p.full_name, sum(s.points)::int as points
  from public.game_scores s join public.profiles p on p.id = s.user_id
  where s.created_at > now() - interval '7 days'
  group by s.user_id, p.full_name
  order by points desc;

-- ---------- Events ---------------------------------------------------
create table public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  starts_at timestamptz not null,
  ends_at timestamptz,
  location text,
  cover_url text,
  capacity int,
  ministry_id uuid references public.ministries on delete set null,
  is_home_meeting boolean not null default false,   -- home prayer invites
  created_at timestamptz not null default now()
);
create table public.event_rsvps (
  event_id uuid references public.events on delete cascade,
  user_id uuid default auth.uid() references public.profiles on delete cascade,
  checked_in_at timestamptz,                         -- QR check-in
  created_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

-- ---------- Ride ministry -------------------------------------------
create type public.ride_status as enum ('requested', 'accepted', 'enroute', 'arrived', 'completed', 'cancelled');
create table public.rides (
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null default auth.uid() references public.profiles on delete cascade,
  volunteer_id uuid references public.profiles on delete set null,
  pickup_label text not null,
  pickup_lat double precision not null,
  pickup_lng double precision not null,
  dropoff_label text not null default 'Agape International Church',
  requested_for text not null,     -- e.g. "Sun 9:15 AM" (or change to timestamptz)
  seats int not null default 1 check (seats between 1 and 8),
  notes text,
  status public.ride_status not null default 'requested',
  created_at timestamptz not null default now()
);
create table public.ride_locations (
  id bigint generated always as identity primary key,
  ride_id uuid not null references public.rides on delete cascade,
  lat double precision not null,
  lng double precision not null,
  heading double precision,
  recorded_at timestamptz not null default now()
);
create index on public.ride_locations (ride_id, recorded_at desc);
create table public.volunteer_shifts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references public.profiles on delete cascade,
  team text not null,              -- driving | ushering | kids | tech …
  starts_at timestamptz not null,
  ends_at timestamptz not null
);

-- ---------- Giving ---------------------------------------------------
create table public.campaigns (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  goal numeric(12,3) not null,
  raised numeric(12,3) not null default 0,
  cover_url text,
  active boolean not null default true
);
create table public.donations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid default auth.uid() references public.profiles on delete set null,
  campaign_id uuid references public.campaigns on delete set null,
  fund text not null default 'Tithe',
  amount numeric(12,3) not null check (amount > 0),
  currency text not null default 'KWD',
  frequency text not null default 'once',   -- once | monthly
  status text not null default 'pending',   -- set to 'succeeded' by the payment webhook
  provider_ref text,
  created_at timestamptz not null default now()
);
create or replace function public.apply_donation() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.status = 'succeeded' and (old is null or old.status <> 'succeeded') and new.campaign_id is not null then
    update public.campaigns set raised = raised + new.amount where id = new.campaign_id;
  end if;
  return new;
end $$;
create trigger donations_apply after insert or update on public.donations
  for each row execute function public.apply_donation();

-- ---------- Notifications, AI usage ---------------------------------
create table public.push_tokens (
  user_id uuid not null default auth.uid() references public.profiles on delete cascade,
  token text not null,
  platform text,
  primary key (user_id, token)
);
create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles on delete cascade,   -- null = broadcast
  kind text not null,              -- new_lesson | ride_assigned | message | announcement
  payload jsonb not null default '{}',
  sent_at timestamptz,
  created_at timestamptz not null default now()
);
create table public.ai_usage (
  id bigint generated always as identity primary key,
  user_id uuid not null references public.profiles on delete cascade,
  tokens int,
  created_at timestamptz not null default now()
);

-- =====================================================================
-- ROW LEVEL SECURITY
-- =====================================================================
do $$ declare t text; begin
  foreach t in array array['profiles','ministries','ministry_members','series','videos','documents','courses','modules','lessons',
    'lesson_progress','sermon_notes','conversations','conversation_members','messages','prayer_requests','prayer_reactions',
    'care_requests','question_packs','questions','game_scores','events','event_rsvps','rides','ride_locations','volunteer_shifts',
    'campaigns','donations','push_tokens','notifications','ai_usage']
  loop execute format('alter table public.%I enable row level security', t); end loop;
end $$;

-- public, read-only content (staff manage it)
do $$ declare t text; begin
  foreach t in array array['ministries','series','videos','documents','courses','modules','lessons','question_packs','questions','events','campaigns']
  loop
    execute format('create policy "read %1$s" on public.%1$I for select using (true)', t);
    execute format('create policy "staff write %1$s" on public.%1$I for all using (public.is_staff()) with check (public.is_staff())', t);
  end loop;
end $$;

-- profiles
create policy "profiles readable by members" on public.profiles for select to authenticated using (true);
create policy "update own profile" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid() and role = public.my_role());  -- members can't promote themselves
create policy "staff manage profiles" on public.profiles for all using (public.is_staff());

-- own-row tables
do $$ declare t text; begin
  foreach t in array array['lesson_progress','sermon_notes','push_tokens','volunteer_shifts']
  loop execute format('create policy "own %1$s" on public.%1$I for all using (user_id = auth.uid()) with check (user_id = auth.uid())', t); end loop;
end $$;

-- ministries membership
create policy "see memberships" on public.ministry_members for select to authenticated using (true);
create policy "join/leave" on public.ministry_members for all using (user_id = auth.uid()) with check (user_id = auth.uid() and is_leader = false);

-- messaging: members of a conversation only; announcements readable by everyone, written by staff
create policy "see my conversations" on public.conversations for select using (
  kind = 'announcement' or exists (select 1 from public.conversation_members m where m.conversation_id = conversations.id and m.user_id = auth.uid()) or public.is_staff());
create policy "see my memberships" on public.conversation_members for select using (user_id = auth.uid() or public.is_staff());
create policy "read messages" on public.messages for select using (
  exists (select 1 from public.conversations c where c.id = conversation_id and (c.kind = 'announcement'
    or exists (select 1 from public.conversation_members m where m.conversation_id = c.id and m.user_id = auth.uid()))));
create policy "send messages" on public.messages for insert with check (
  sender_id = auth.uid() and exists (select 1 from public.conversations c where c.id = conversation_id and (
    (c.kind <> 'announcement' and exists (select 1 from public.conversation_members m where m.conversation_id = c.id and m.user_id = auth.uid()))
    or (c.kind = 'announcement' and public.is_staff()))));

-- prayer
create policy "read prayer wall" on public.prayer_requests for select to authenticated using (not hidden or user_id = auth.uid() or public.is_staff());
create policy "post prayer" on public.prayer_requests for insert with check (user_id = auth.uid());
create policy "edit own prayer" on public.prayer_requests for update using (user_id = auth.uid() or public.is_staff());
create policy "own reactions" on public.prayer_reactions for select using (user_id = auth.uid());
create policy "own care requests" on public.care_requests for insert with check (user_id = auth.uid());
create policy "staff read care" on public.care_requests for select using (public.is_staff() or user_id = auth.uid());

-- games
create policy "scores readable" on public.game_scores for select to authenticated using (true);
create policy "post own score" on public.game_scores for insert with check (user_id = auth.uid());

-- events
create policy "own rsvps" on public.event_rsvps for all using (user_id = auth.uid() or public.is_staff()) with check (user_id = auth.uid() or public.is_staff());

-- rides
create policy "member sees own rides; volunteers see open + assigned" on public.rides for select using (
  member_id = auth.uid() or volunteer_id = auth.uid() or (public.is_volunteer() and status = 'requested') or public.is_staff());
create policy "member requests ride" on public.rides for insert with check (member_id = auth.uid());
create policy "member cancels own" on public.rides for update using (member_id = auth.uid()) with check (member_id = auth.uid());
create policy "volunteer accepts / updates" on public.rides for update using (
  public.is_volunteer() and (status = 'requested' or volunteer_id = auth.uid())) with check (volunteer_id = auth.uid());
create policy "volunteer posts location" on public.ride_locations for insert with check (
  exists (select 1 from public.rides r where r.id = ride_id and r.volunteer_id = auth.uid()));
create policy "ride parties read location" on public.ride_locations for select using (
  exists (select 1 from public.rides r where r.id = ride_id and (r.member_id = auth.uid() or r.volunteer_id = auth.uid())));

-- giving
create policy "own donations" on public.donations for select using (user_id = auth.uid() or public.is_staff());
create policy "create pending donation" on public.donations for insert with check (user_id = auth.uid() and status = 'pending');

-- notifications
create policy "own notifications" on public.notifications for select using (user_id = auth.uid() or user_id is null);
create policy "own ai usage" on public.ai_usage for select using (user_id = auth.uid());

-- realtime feeds (messaging, live ride tracking)
alter publication supabase_realtime add table public.messages, public.ride_locations, public.rides, public.prayer_requests;

-- =====================================================================
-- CMS: website + app content edited in /admin
-- =====================================================================
create table public.site_content (
  key text primary key,                 -- 'site'
  data jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles on delete set null
);
alter table public.site_content enable row level security;
create policy "anyone reads site content" on public.site_content for select using (true);
create policy "staff edit site content" on public.site_content for all using (public.is_staff()) with check (public.is_staff());

create table public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text,
  created_by uuid default auth.uid() references public.profiles on delete set null,
  created_at timestamptz not null default now()
);
alter table public.announcements enable row level security;
create policy "members read announcements" on public.announcements for select using (true);
create policy "staff manage announcements" on public.announcements for all using (public.is_staff()) with check (public.is_staff());

-- Public image bucket for uploads from /admin (Supabase Storage)
do $$ begin
  if exists (select 1 from information_schema.schemata where schema_name = 'storage') then
    insert into storage.buckets (id, name, public) values ('media', 'media', true) on conflict (id) do nothing;
    execute 'create policy "public read media" on storage.objects for select using (bucket_id = ''media'')';
    execute 'create policy "staff upload media" on storage.objects for insert with check (bucket_id = ''media'' and public.is_staff())';
    execute 'create policy "staff update media" on storage.objects for update using (bucket_id = ''media'' and public.is_staff())';
    execute 'create policy "staff delete media" on storage.objects for delete using (bucket_id = ''media'' and public.is_staff())';
  end if;
end $$;

alter publication supabase_realtime add table public.site_content, public.announcements;

-- =====================================================================
-- STAFF ANALYTICS (admin dashboard)
-- =====================================================================
create view public.staff_stats with (security_invoker = true) as
  select
    (select count(*) from public.profiles) as members,
    (select count(distinct user_id) from public.lesson_progress where completed_at > now() - interval '30 days') as active_learners,
    (select coalesce(sum(views),0) from public.videos) as total_views,
    (select count(*) from public.rides where status = 'completed') as rides_completed,
    (select coalesce(sum(amount),0) from public.donations where status = 'succeeded' and created_at > date_trunc('month', now())) as giving_this_month;

-- ===== migrations/20261002000000_publish_ready.sql
-- =====================================================================
-- AGAPE — publish-ready additions (run after the initial schema)
-- • App content managed in /admin: sermons, courses + lessons, study guides,
--   games, groups (each with a group chat)
-- • Member features: saved sermons, sermon live chat, RSVPs to the events
--   staff publish in /admin, direct messages, unpray, account deletion
-- • Privacy: email and phone are never readable by other members
-- =====================================================================

-- ---------- Profiles: private contact details ------------------------
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists car text;          -- volunteer drivers: "White Toyota Innova · KW 38 7456"

-- keep the email copy in sync on sign-up (used by the admin member list only)
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, avatar_url, email)
  values (new.id, coalesce(nullif(new.raw_user_meta_data->>'full_name', ''), split_part(new.email, '@', 1)), new.raw_user_meta_data->>'avatar_url', new.email)
  on conflict (id) do nothing;
  return new;
end $$;
update public.profiles p set email = u.email from auth.users u where u.id = p.id and p.email is null;

-- other members may read names and roles, never email or phone
revoke select on public.profiles from anon, authenticated;
grant select (id, full_name, avatar_url, role, language, kids_mode, created_at, car) on public.profiles to authenticated;
revoke update on public.profiles from anon, authenticated;
grant update (full_name, avatar_url, phone, language, kids_mode, car) on public.profiles to authenticated;

-- a member's own private details
create or replace function public.my_contact() returns table (email text, phone text)
language sql stable security definer set search_path = public as $$
  select email, phone from public.profiles where id = auth.uid();
$$;

-- staff-only member list (with email) for /admin
create or replace function public.staff_members()
returns table (id uuid, full_name text, email text, phone text, role public.user_role, created_at timestamptz)
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.is_staff() then raise exception 'staff only'; end if;
  return query select p.id, p.full_name, p.email, p.phone, p.role, p.created_at from public.profiles p order by p.created_at desc;
end $$;

-- only admins can make admins; staff can set member / volunteer / staff
-- Guards run as the caller (security invoker) so they only restrict requests from the app;
-- the SQL editor, the service role and our own security-definer functions pass straight through.
create or replace function public.guard_profile_role() returns trigger
language plpgsql set search_path = public as $$
begin
  if current_user not in ('authenticated', 'anon') then return new; end if;
  if new.role is distinct from old.role then
    if not public.is_staff() then raise exception 'not allowed to change roles'; end if;
    if (new.role = 'admin' or old.role = 'admin') and public.my_role() <> 'admin' then raise exception 'only an admin can change admin roles'; end if;
  end if;
  return new;
end $$;
drop trigger if exists profiles_guard_role on public.profiles;
create trigger profiles_guard_role before update on public.profiles for each row execute function public.guard_profile_role();
grant update (role) on public.profiles to authenticated;   -- the trigger + "staff manage profiles" policy decide who may

-- Apple requires in-app account deletion
create or replace function public.delete_my_account() returns void
language plpgsql security definer set search_path = public, auth as $$
begin
  if auth.uid() is null then raise exception 'not signed in'; end if;
  delete from auth.users where id = auth.uid();   -- cascades to profiles and everything the member owns
end $$;

-- ---------- Sermons ----------------------------------------------------
alter table public.series add column if not exists color text;
alter table public.series add column if not exists position int not null default 0;
alter table public.videos add column if not exists cover_url text;

create table if not exists public.saved_videos (
  user_id uuid not null default auth.uid() references public.profiles on delete cascade,
  video_id uuid not null references public.videos on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, video_id)
);
alter table public.saved_videos enable row level security;
create policy "own saved videos" on public.saved_videos for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.count_view(video uuid) returns void
language sql security definer set search_path = public as $$
  update public.videos set views = views + 1 where id = video;
$$;

-- live chat beside a sermon / live stream
create table if not exists public.live_chat (
  id bigint generated always as identity primary key,
  video_id uuid not null references public.videos on delete cascade,
  user_id uuid not null default auth.uid() references public.profiles on delete cascade,
  body text not null check (char_length(body) between 1 and 300),
  hidden boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists live_chat_video on public.live_chat (video_id, created_at desc);
alter table public.live_chat enable row level security;
create policy "read live chat" on public.live_chat for select to authenticated using (not hidden or public.is_staff());
create policy "post live chat" on public.live_chat for insert to authenticated with check (user_id = auth.uid());
create policy "staff moderate live chat" on public.live_chat for update using (public.is_staff());
create policy "delete own or staff" on public.live_chat for delete using (user_id = auth.uid() or public.is_staff());

-- ---------- Courses: lessons hang straight off a course ---------------
alter table public.courses add column if not exists color text;
alter table public.courses add column if not exists position int not null default 0;
alter table public.lessons alter column module_id drop not null;
alter table public.lessons add column if not exists course_id uuid references public.courses on delete cascade;
alter table public.lessons add column if not exists url text;        -- YouTube link, PDF link or any web page
alter table public.lessons add column if not exists body text;       -- optional reading / notes
create index if not exists lessons_course on public.lessons (course_id, position);
update public.lessons l set course_id = m.course_id from public.modules m where m.id = l.module_id and l.course_id is null;

-- ---------- Study guides ----------------------------------------------
alter table public.documents alter column r2_key drop not null;
alter table public.documents add column if not exists url text;
alter table public.documents add column if not exists color text;
alter table public.documents add column if not exists position int not null default 0;

-- ---------- Events: RSVPs to the events staff publish in /admin -------
-- Website and app events live in site_content (edited in /admin), so RSVPs key on the event's stable key.
create table if not exists public.rsvps (
  event_key text not null check (char_length(event_key) <= 200),
  event_title text,
  user_id uuid not null default auth.uid() references public.profiles on delete cascade,
  checked_in_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (event_key, user_id)
);
alter table public.rsvps enable row level security;
create policy "own rsvps" on public.rsvps for select using (user_id = auth.uid() or public.is_staff());
create policy "rsvp" on public.rsvps for insert with check (user_id = auth.uid());
create policy "cancel rsvp" on public.rsvps for delete using (user_id = auth.uid() or public.is_staff());
create policy "staff check in" on public.rsvps for update using (public.is_staff()) with check (public.is_staff());

create or replace view public.rsvp_counts with (security_invoker = false) as
  select event_key, count(*)::int as going from public.rsvps group by event_key;
grant select on public.rsvp_counts to anon, authenticated;

-- staff: who's coming
create or replace function public.staff_rsvps()
returns table (event_key text, event_title text, user_id uuid, full_name text, email text, phone text, checked_in_at timestamptz, created_at timestamptz)
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.is_staff() then raise exception 'staff only'; end if;
  return query select r.event_key, r.event_title, r.user_id, p.full_name, p.email, p.phone, r.checked_in_at, r.created_at
    from public.rsvps r join public.profiles p on p.id = r.user_id order by r.created_at desc;
end $$;

-- ---------- Prayer wall -------------------------------------------------
create or replace function public.unpray(request_id uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  delete from public.prayer_reactions where prayer_reactions.request_id = unpray.request_id and user_id = auth.uid();
  if found then
    update public.prayer_requests set pray_count = greatest(0, pray_count - 1) where id = unpray.request_id;
  end if;
end $$;

-- members may only edit the text / answered flag of their own requests
create or replace function public.guard_prayer_update() returns trigger
language plpgsql set search_path = public as $$
begin
  if current_user in ('authenticated', 'anon') and not public.is_staff() then
    new.pray_count := old.pray_count;
    new.hidden := old.hidden;
    new.user_id := old.user_id;
    new.anonymous := old.anonymous;
  end if;
  return new;
end $$;
drop trigger if exists prayer_guard on public.prayer_requests;
create trigger prayer_guard before update on public.prayer_requests for each row execute function public.guard_prayer_update();
create policy "staff delete prayer" on public.prayer_requests for delete using (public.is_staff() or user_id = auth.uid());

-- the wall view also tells the app which requests are mine
create or replace view public.prayer_wall with (security_invoker = true) as
  select r.id, r.body, r.anonymous, r.pray_count, r.answered, r.created_at,
         case when r.anonymous then null else p.full_name end as author_name,
         (r.user_id = auth.uid()) as mine
  from public.prayer_requests r left join public.profiles p on p.id = r.user_id
  where not r.hidden;

-- ---------- Pastoral care: staff can update status --------------------
create policy "staff update care" on public.care_requests for update using (public.is_staff()) with check (public.is_staff());
create or replace function public.staff_care()
returns table (id uuid, kind text, details text, status text, created_at timestamptz, full_name text, email text, phone text)
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.is_staff() then raise exception 'staff only'; end if;
  return query select c.id, c.kind, c.details, c.status, c.created_at, p.full_name, p.email, p.phone
    from public.care_requests c join public.profiles p on p.id = c.user_id order by c.created_at desc;
end $$;

-- ---------- Rides --------------------------------------------------------
-- members may only cancel; volunteers may only move a ride along
create or replace function public.guard_ride_update() returns trigger
language plpgsql set search_path = public as $$
begin
  if current_user not in ('authenticated', 'anon') or public.is_staff() then return new; end if;
  if auth.uid() = old.member_id and (old.volunteer_id is distinct from auth.uid()) then
    if new.status <> 'cancelled' then raise exception 'members can only cancel a ride'; end if;
    new := old; new.status := 'cancelled';
    return new;
  end if;
  -- volunteer
  new.member_id := old.member_id; new.pickup_label := old.pickup_label; new.pickup_lat := old.pickup_lat; new.pickup_lng := old.pickup_lng;
  new.requested_for := old.requested_for; new.seats := old.seats; new.notes := old.notes; new.dropoff_label := old.dropoff_label;
  if old.status = 'requested' and new.status = 'cancelled' then raise exception 'only the member can cancel'; end if;
  if new.status = 'requested' then new.volunteer_id := null; end if;   -- volunteer hands the ride back
  return new;
end $$;
drop trigger if exists rides_guard on public.rides;
create trigger rides_guard before update on public.rides for each row execute function public.guard_ride_update();

drop policy if exists "volunteer accepts / updates" on public.rides;
create policy "volunteer accepts / updates" on public.rides for update using (
  public.is_volunteer() and (status = 'requested' or volunteer_id = auth.uid()))
  with check (volunteer_id = auth.uid() or (status = 'requested' and volunteer_id is null));
create policy "staff manage rides" on public.rides for update using (public.is_staff()) with check (public.is_staff());

-- phone number of the other person on a ride (only while the ride is active)
create or replace function public.ride_phone(ride uuid) returns text
language sql stable security definer set search_path = public as $$
  select case when r.member_id = auth.uid() then v.phone when r.volunteer_id = auth.uid() then m.phone end
  from public.rides r
  join public.profiles m on m.id = r.member_id
  left join public.profiles v on v.id = r.volunteer_id
  where r.id = ride and r.status in ('accepted', 'enroute', 'arrived');
$$;

create or replace function public.staff_rides()
returns table (id uuid, pickup_label text, requested_for text, seats int, notes text, status public.ride_status, created_at timestamptz,
               member_id uuid, member text, member_phone text, volunteer_id uuid, volunteer text)
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.is_staff() then raise exception 'staff only'; end if;
  return query select r.id, r.pickup_label, r.requested_for, r.seats, r.notes, r.status, r.created_at,
    r.member_id, m.full_name, m.phone, r.volunteer_id, v.full_name
    from public.rides r join public.profiles m on m.id = r.member_id left join public.profiles v on v.id = r.volunteer_id
    order by r.created_at desc limit 300;
end $$;

-- ---------- Groups (ministries) with a group chat each ----------------
alter table public.ministries add column if not exists position int not null default 0;
alter table public.conversations add column if not exists created_by uuid default auth.uid() references public.profiles on delete set null;

create or replace function public.ministry_conversation() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.conversations (kind, name, ministry_id) values ('group', new.name, new.id);
  return new;
end $$;
drop trigger if exists ministries_conversation on public.ministries;
create trigger ministries_conversation after insert on public.ministries for each row execute function public.ministry_conversation();
create or replace function public.ministry_rename() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  update public.conversations set name = new.name where ministry_id = new.id and kind = 'group';
  return new;
end $$;
drop trigger if exists ministries_rename on public.ministries;
create trigger ministries_rename after update of name on public.ministries for each row execute function public.ministry_rename();
insert into public.conversations (kind, name, ministry_id)
  select 'group', m.name, m.id from public.ministries m
  where not exists (select 1 from public.conversations c where c.ministry_id = m.id and c.kind = 'group');

-- one church-wide announcements channel
insert into public.conversations (kind, name)
  select 'announcement', 'Agape Family' where not exists (select 1 from public.conversations where kind = 'announcement');

create or replace function public.in_conversation(conv uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.conversation_members where conversation_id = conv and user_id = auth.uid());
$$;

-- members see who else is in their conversations (needed for DM names); no recursion via the definer helper
drop policy if exists "see my memberships" on public.conversation_members;
create policy "see conversation members" on public.conversation_members for select using (public.in_conversation(conversation_id) or public.is_staff());
create policy "mark read" on public.conversation_members for update using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.join_group(ministry uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare conv uuid;
begin
  if auth.uid() is null then raise exception 'not signed in'; end if;
  insert into public.ministry_members (ministry_id, user_id) values (ministry, auth.uid()) on conflict do nothing;
  select id into conv from public.conversations where ministry_id = ministry and kind = 'group' limit 1;
  if conv is not null then
    insert into public.conversation_members (conversation_id, user_id, last_read_at) values (conv, auth.uid(), now()) on conflict do nothing;
  end if;
  return conv;
end $$;

create or replace function public.leave_group(ministry uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  delete from public.ministry_members where ministry_id = ministry and user_id = auth.uid();
  delete from public.conversation_members where user_id = auth.uid()
    and conversation_id in (select id from public.conversations where ministry_id = ministry and kind = 'group');
end $$;

-- start (or reopen) a direct conversation with another member
create or replace function public.start_direct(other uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare conv uuid;
begin
  if auth.uid() is null then raise exception 'not signed in'; end if;
  if other = auth.uid() then raise exception 'cannot message yourself'; end if;
  if not exists (select 1 from public.profiles where id = other) then raise exception 'member not found'; end if;
  select c.id into conv from public.conversations c
    where c.kind = 'direct'
      and exists (select 1 from public.conversation_members a where a.conversation_id = c.id and a.user_id = auth.uid())
      and exists (select 1 from public.conversation_members b where b.conversation_id = c.id and b.user_id = other)
    limit 1;
  if conv is null then
    insert into public.conversations (kind) values ('direct') returning id into conv;
    insert into public.conversation_members (conversation_id, user_id, last_read_at) values (conv, auth.uid(), now()), (conv, other, null);
  end if;
  return conv;
end $$;

-- the member's chat list with the latest message and unread count
create or replace function public.my_chats()
returns table (id uuid, kind public.conversation_kind, name text, ministry_id uuid, last_body text, last_at timestamptz, last_sender text, unread int, members int)
language sql stable security definer set search_path = public as $$
  with mine as (
    select c.*, cm.last_read_at from public.conversations c
    join public.conversation_members cm on cm.conversation_id = c.id and cm.user_id = auth.uid()
    union all
    select c.*, null::timestamptz from public.conversations c
    where c.kind = 'announcement' and not exists (select 1 from public.conversation_members cm where cm.conversation_id = c.id and cm.user_id = auth.uid())
  )
  select m.id, m.kind,
    coalesce(m.name, (select p.full_name from public.conversation_members o join public.profiles p on p.id = o.user_id
                      where o.conversation_id = m.id and o.user_id <> auth.uid() limit 1), 'Conversation'),
    m.ministry_id, lm.body, lm.created_at, lm.sender,
    (select count(*)::int from public.messages x where x.conversation_id = m.id and x.sender_id <> auth.uid()
       and (m.last_read_at is null or x.created_at > m.last_read_at)),
    (select count(*)::int from public.conversation_members y where y.conversation_id = m.id)
  from mine m
  left join lateral (
    select msg.body, msg.created_at, p.full_name as sender from public.messages msg join public.profiles p on p.id = msg.sender_id
    where msg.conversation_id = m.id order by msg.created_at desc limit 1
  ) lm on true
  where auth.uid() is not null
  order by coalesce(lm.created_at, m.created_at) desc;
$$;

create or replace function public.mark_read(conv uuid) returns void
language sql security definer set search_path = public as $$
  update public.conversation_members set last_read_at = now() where conversation_id = conv and user_id = auth.uid();
$$;

-- group member counts (readable by anyone browsing groups)
create or replace view public.ministry_counts with (security_invoker = false) as
  select ministry_id, count(*)::int as members from public.ministry_members group by ministry_id;
grant select on public.ministry_counts to anon, authenticated;

-- ---------- Games ---------------------------------------------------------
create or replace view public.my_points with (security_invoker = true) as
  select coalesce(sum(points), 0)::int as points from public.game_scores where user_id = auth.uid();

-- ---------- Announcements reach the app's News tab in real time -------
-- (already in the realtime publication)

-- ---------- Realtime for the new feeds --------------------------------
alter publication supabase_realtime add table public.live_chat, public.rsvps;

-- ---------- Staff dashboard numbers -----------------------------------
drop view if exists public.staff_stats;
create view public.staff_stats with (security_invoker = true) as
  select
    (select count(*) from public.profiles) as members,
    (select count(*) from public.profiles where created_at > now() - interval '30 days') as new_members,
    (select count(distinct user_id) from public.lesson_progress where completed_at > now() - interval '30 days') as active_learners,
    (select coalesce(sum(views),0) from public.videos) as total_views,
    (select count(*) from public.rides where status = 'completed') as rides_completed,
    (select count(*) from public.rides where status = 'requested') as rides_waiting,
    (select count(*) from public.prayer_requests where not hidden) as prayers,
    (select count(*) from public.care_requests where status = 'open') as care_open,
    (select coalesce(sum(amount),0) from public.donations where status = 'succeeded' and created_at > date_trunc('month', now())) as giving_this_month;

-- ===== migrations/20261003000000_bible_songs.sql
-- Bible (highlights, bookmarks, verse notes) and the worship song book (chord charts + set lists).
-- Safe to run more than once. On an existing project paste this file into Supabase → SQL Editor → Run.

-- ---------------------------------------------------------------- Bible marks (private to each member)
create table if not exists public.bible_marks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references public.profiles on delete cascade,
  kind text not null check (kind in ('highlight', 'bookmark', 'note')),
  book int not null check (book between 1 and 66),
  chapter int not null check (chapter > 0),
  verse int not null check (verse > 0),
  color text,
  note text,
  translation text,
  verse_text text,
  created_at timestamptz not null default now(),
  unique (user_id, kind, book, chapter, verse)
);
alter table public.bible_marks enable row level security;
drop policy if exists "own bible marks" on public.bible_marks;
create policy "own bible marks" on public.bible_marks for all using (user_id = auth.uid()) with check (user_id = auth.uid());
grant select, insert, update, delete on public.bible_marks to authenticated;

-- ---------------------------------------------------------------- song book
create table if not exists public.songs (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  author text,
  original_key text not null default 'G',
  tempo int,
  time_sig text default '4/4',
  language text not null default 'en',
  tags text[] not null default '{}',
  body text not null,              -- ChordPro: "{Verse 1}\n[G]Amazing [G7]grace …"
  youtube_id text,
  copyright text,
  published boolean not null default true,
  position int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.set_lists (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references public.profiles on delete cascade,
  title text not null,
  service_date date,
  items jsonb not null default '[]'::jsonb,   -- [{ "song": "amazing-grace", "key": "A" }]
  shared boolean not null default false,      -- worship-team sets everyone can see (staff only)
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.songs enable row level security;
alter table public.set_lists enable row level security;
drop policy if exists "read songs" on public.songs;
drop policy if exists "staff write songs" on public.songs;
create policy "read songs" on public.songs for select using (published or public.is_staff());
create policy "staff write songs" on public.songs for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists "read set lists" on public.set_lists;
drop policy if exists "own set lists" on public.set_lists;
drop policy if exists "edit own set lists" on public.set_lists;
drop policy if exists "delete own set lists" on public.set_lists;
create policy "read set lists" on public.set_lists for select using (shared or owner_id = auth.uid() or public.is_staff());
create policy "own set lists" on public.set_lists for insert with check (owner_id = auth.uid() and (not shared or public.is_staff()));
create policy "edit own set lists" on public.set_lists for update using (owner_id = auth.uid() or public.is_staff()) with check ((owner_id = auth.uid() and (not shared or public.is_staff())) or public.is_staff());
create policy "delete own set lists" on public.set_lists for delete using (owner_id = auth.uid() or public.is_staff());
grant select on public.songs to anon, authenticated;
grant insert, update, delete on public.songs to authenticated;
grant select, insert, update, delete on public.set_lists to authenticated;
create index if not exists songs_position_idx on public.songs (position);

-- ---------------------------------------------------------------- starter hymns (public domain: words and music before 1929)
insert into public.songs (slug, title, author, original_key, tempo, time_sig, tags, body, copyright, position) values
($s$amazing-grace$s$, $s$Amazing Grace$s$, $s$John Newton, 1779 · music: New Britain$s$, 'G', 76, '3/4', array['hymn', 'classic', 'worship']::text[], $s${Verse 1}
A[G]mazing grace! How [G7]sweet the [C]sound
That [G]saved a wretch like [D]me!
I [G]once was lost, but [G7]now am [C]found;
Was [G]blind, but [D]now I [G]see.

{Verse 2}
'Twas [G]grace that taught my [G7]heart to [C]fear,
And [G]grace my fears re[D]lieved;
How [G]precious did that [G7]grace ap[C]pear
The [G]hour I [D]first be[G]lieved.

{Verse 3}
Through [G]many dangers, [G7]toils and [C]snares,
I [G]have already [D]come;
'Tis [G]grace hath brought me [G7]safe thus [C]far,
And [G]grace will [D]lead me [G]home.

{Verse 4}
The [G]Lord has promised [G7]good to [C]me,
His [G]word my hope se[D]cures;
He [G]will my shield and [G7]portion [C]be,
As [G]long as [D]life en[G]dures.

{Verse 5}
When [G]we've been there ten [G7]thousand [C]years,
Bright [G]shining as the [D]sun,
We've [G]no less days to [G7]sing God's [C]praise
Than [G]when we'd [D]first be[G]gun.$s$, 'Public domain', 1),
($s$doxology$s$, $s$Doxology (Praise God, from Whom All Blessings Flow)$s$, $s$Thomas Ken, 1674 · music: Old Hundredth$s$, 'G', 84, '4/4', array['hymn', 'praise', 'classic']::text[], $s${Doxology}
[G]Praise God, from [D]whom all [Em]blessings [D]flow;
[G]Praise Him, all [C]creatures [D]here be[G]low;
[G]Praise Him a[D]bove, ye [Em]heavenly [D]host;
[G]Praise Father, [C]Son, and [D]Holy [G]Ghost.
[C]A[G]men.$s$, 'Public domain', 2),
($s$holy-holy-holy$s$, $s$Holy, Holy, Holy! Lord God Almighty$s$, $s$Reginald Heber, 1826 · music: Nicaea, John B. Dykes$s$, 'D', 84, '4/4', array['hymn', 'worship', 'classic']::text[], $s${Verse 1}
[D]Holy, holy, [Bm]holy! [G]Lord God Al[D]mighty!
[D]Early in the [A]morning our [Bm]song shall [E7]rise to [A]Thee;
[D]Holy, holy, [Bm]holy, [G]merciful and [D]mighty!
[G]God in three [D]Persons, [Em]bless[A7]ed Trini[D]ty!

{Verse 2}
[D]Holy, holy, [Bm]holy! [G]All the saints a[D]dore Thee,
[D]Casting down their [A]golden crowns a[Bm]round the [E7]glassy [A]sea;
[D]Cherubim and [Bm]seraphim [G]falling down be[D]fore Thee,
[G]Which wert, and [D]art, and [Em]ever[A7]more shalt [D]be.

{Verse 3}
[D]Holy, holy, [Bm]holy! [G]Though the darkness [D]hide Thee,
[D]Though the eye of [A]sinful man Thy [Bm]glory [E7]may not [A]see;
[D]Only Thou art [Bm]holy; [G]there is none be[D]side Thee,
[G]Perfect in [D]power, in [Em]love, and [A7]puri[D]ty.

{Verse 4}
[D]Holy, holy, [Bm]holy! [G]Lord God Al[D]mighty!
[D]All Thy works shall [A]praise Thy name, in [Bm]earth, and [E7]sky, and [A]sea;
[D]Holy, holy, [Bm]holy; [G]merciful and [D]mighty!
[G]God in three [D]Persons, [Em]bless[A7]ed Trini[D]ty!$s$, 'Public domain', 3),
($s$jesus-loves-me$s$, $s$Jesus Loves Me$s$, $s$Anna B. Warner, 1860 · music: William B. Bradbury, 1862$s$, 'C', 96, '4/4', array['kids', 'hymn', 'classic']::text[], $s${Verse 1}
[C]Jesus loves me! [F]This I [C]know,
For the Bible [G]tells me [C]so;
Little ones to [F]Him be[C]long;
They are weak, but [G]He is [C]strong.

{Chorus}
[C]Yes, Jesus [F]loves me!
[C]Yes, Jesus [G]loves me!
[C]Yes, Jesus [F]loves me!
The [C]Bible [G]tells me [C]so.

{Verse 2}
[C]Jesus loves me! [F]He who [C]died
Heaven's gate to [G]open [C]wide;
He will wash a[F]way my [C]sin,
Let His little [G]child come [C]in.

{Verse 3}
[C]Jesus loves me! [F]He will [C]stay
Close beside me [G]all the [C]way;
Thou hast bled and [F]died for [C]me,
I will henceforth [G]live for [C]Thee.$s$, 'Public domain', 4),
($s$it-is-well-with-my-soul$s$, $s$It Is Well with My Soul$s$, $s$Horatio G. Spafford, 1873 · music: Ville du Havre, Philip P. Bliss$s$, 'C', 72, '4/4', array['hymn', 'classic', 'worship']::text[], $s${Verse 1}
When [C]peace like a [Am]river at[F]tendeth my [C]way,
When [Am]sorrows like [D7]sea billows [G]roll;
What[C]ever my [C7]lot, Thou hast [F]taught me to [Fm]say,
It is [C]well, it is [G7]well with my [C]soul.

{Refrain}
It is [G]well (it is [G7]well)
With my [C]soul (with my soul),
It is [F]well, it is [C]well with my [G7]soul.

{Verse 2}
Though [C]Satan should [Am]buffet, though [F]trials should [C]come,
Let [Am]this blest as[D7]surance con[G]trol,
That [C]Christ has re[C7]garded my [F]helpless es[Fm]tate,
And hath [C]shed His own [G7]blood for my [C]soul.

{Verse 3}
My [C]sin, oh, the [Am]bliss of this [F]glorious [C]thought!
My [Am]sin, not in [D7]part but the [G]whole,
Is [C]nailed to the [C7]cross, and I [F]bear it no [Fm]more,
Praise the [C]Lord, praise the [G7]Lord, O my [C]soul!

{Verse 4}
And, [C]Lord, haste the [Am]day when my [F]faith shall be [C]sight,
The [Am]clouds be rolled [D7]back as a [G]scroll;
The [C]trump shall re[C7]sound, and the [F]Lord shall de[Fm]scend,
Even [C]so, it is [G7]well with my [C]soul.$s$, 'Public domain', 5),
($s$blessed-assurance$s$, $s$Blessed Assurance$s$, $s$Fanny J. Crosby, 1873 · music: Phoebe P. Knapp$s$, 'D', 100, '9/8', array['hymn', 'praise', 'classic']::text[], $s${Verse 1}
[D]Blessed as[G]surance, [D]Jesus is mine!
[D]O what a [E7]foretaste of [A]glory di[A7]vine!
[D]Heir of sal[G]vation, [D]purchase of God,
[G]Born of His [D]Spirit, [A7]washed in His [D]blood.

{Refrain}
[D]This is my [G]story, [D]this is my song,
[D]Praising my [E7]Savior [A]all the day [A7]long;
[D]This is my [G]story, [D]this is my song,
[G]Praising my [D]Savior [A7]all the day [D]long.

{Verse 2}
[D]Perfect sub[G]mission, [D]perfect delight,
[D]Visions of [E7]rapture now [A]burst on my [A7]sight;
[D]Angels de[G]scending [D]bring from above
[G]Echoes of [D]mercy, [A7]whispers of [D]love.

{Verse 3}
[D]Perfect sub[G]mission, [D]all is at rest,
[D]I in my [E7]Savior am [A]happy and [A7]blest,
[D]Watching and [G]waiting, [D]looking above,
[G]Filled with His [D]goodness, [A7]lost in His [D]love.$s$, 'Public domain', 6),
($s$what-a-friend-we-have-in-jesus$s$, $s$What a Friend We Have in Jesus$s$, $s$Joseph M. Scriven, 1855 · music: Converse, Charles C. Converse$s$, 'F', 88, '4/4', array['hymn', 'prayer', 'classic']::text[], $s${Verse 1}
[F]What a friend we [Bb]have in [F]Jesus,
All our sins and [C7]griefs to [F]bear!
What a privilege [Bb]to [F]carry
Everything to [C7]God in [F]prayer!
[C]O what peace we [C7]often for[F]feit,
[C]O what needless [G7]pain we [C]bear,
[F]All because we [Bb]do not [F]carry
Everything to [C7]God in [F]prayer!

{Verse 2}
[F]Have we trials [Bb]and temp[F]tations?
Is there trouble [C7]any[F]where?
We should never [Bb]be dis[F]couraged;
Take it to the [C7]Lord in [F]prayer.
[C]Can we find a [C7]friend so [F]faithful
[C]Who will all our [G7]sorrows [C]share?
[F]Jesus knows our [Bb]every [F]weakness;
Take it to the [C7]Lord in [F]prayer.

{Verse 3}
[F]Are we weak and [Bb]heavy-[F]laden,
Cumbered with a [C7]load of [F]care?
Precious Savior, [Bb]still our [F]refuge;
Take it to the [C7]Lord in [F]prayer.
[C]Do thy friends de[C7]spise, for[F]sake thee?
[C]Take it to the [G7]Lord in [C]prayer!
[F]In His arms He'll [Bb]take and [F]shield thee;
Thou wilt find a [C7]solace [F]there.$s$, 'Public domain', 7),
($s$come-thou-fount$s$, $s$Come, Thou Fount of Every Blessing$s$, $s$Robert Robinson, 1758 · music: Nettleton$s$, 'D', 84, '3/4', array['hymn', 'worship', 'classic']::text[], $s${Verse 1}
[D]Come, Thou Fount of [G]every [D]blessing,
Tune my heart to [A]sing Thy [D]grace;
Streams of mercy, [G]never [D]ceasing,
Call for songs of [A]loudest [D]praise.
[D]Teach me some me[G]lodious [D]sonnet,
[Bm]Sung by flaming [E7]tongues a[A]bove;
[D]Praise the mount! I'm [G]fixed up[D]on it,
Mount of Thy re[A]deeming [D]love.

{Verse 2}
[D]Here I raise mine [G]Ebe[D]nezer;
Hither by Thy [A]help I'm [D]come;
And I hope, by [G]Thy good [D]pleasure,
Safely to ar[A]rive at [D]home.
[D]Jesus sought me [G]when a [D]stranger,
[Bm]Wandering from the [E7]fold of [A]God;
[D]He, to rescue [G]me from [D]danger,
Interposed His [A]precious [D]blood.

{Verse 3}
[D]O to grace how [G]great a [D]debtor
Daily I'm con[A]strained to [D]be!
Let Thy goodness, [G]like a [D]fetter,
Bind my wandering [A]heart to [D]Thee.
[D]Prone to wander, [G]Lord, I [D]feel it,
[Bm]Prone to leave the [E7]God I [A]love;
[D]Here's my heart, O [G]take and [D]seal it,
Seal it for Thy [A]courts a[D]bove.$s$, 'Public domain', 8),
($s$great-is-thy-faithfulness$s$, $s$Great Is Thy Faithfulness$s$, $s$Thomas O. Chisholm, 1923 · music: William M. Runyan, 1923$s$, 'D', 76, '3/4', array['hymn', 'worship', 'classic']::text[], $s${Verse 1}
"Great is Thy [D]faithfulness," [G]O God my [D]Father,
There is no [B7]shadow of [Em]turning with [A7]Thee;
Thou changest [D]not, Thy com[G]passions, they [D]fail not;
As Thou hast [G]been Thou for[A7]ever wilt [D]be.

{Refrain}
"Great is Thy [A7]faithful[D]ness!" "Great is Thy [B7]faithful[Em]ness!"
Morning by [A7]morning new [D]mercies I [A]see;
All I have [D]needed Thy [G]hand hath pro[D]vided;
"Great is Thy [G]faithful[D]ness," [A7]Lord, unto [D]me!

{Verse 2}
Summer and [D]winter, and [G]springtime and [D]harvest,
Sun, moon and [B7]stars in their [Em]courses a[A7]bove,
Join with all [D]nature in [G]manifold [D]witness
To Thy great [G]faithfulness, [A7]mercy and [D]love.

{Verse 3}
Pardon for [D]sin and a [G]peace that en[D]dureth,
Thine own dear [B7]presence to [Em]cheer and to [A7]guide;
Strength for to[D]day and bright [G]hope for to[D]morrow,
Blessings all [G]mine, with ten [A7]thousand be[D]side!$s$, 'Public domain', 9),
($s$be-thou-my-vision$s$, $s$Be Thou My Vision$s$, $s$Ancient Irish, tr. Mary E. Byrne 1905, versified by Eleanor H. Hull 1912 · music: Slane$s$, 'D', 80, '3/4', array['hymn', 'prayer', 'classic']::text[], $s${Verse 1}
[D]Be Thou my [G]Vision, O [D]Lord of my [G]heart;
[G]Naught be all [A]else to me, [Bm]save that Thou [A]art;
[G]Thou my best [D]Thought, by [G]day or by [D]night,
[Bm]Waking or [G]sleeping, Thy [A]presence my [D]light.

{Verse 2}
[D]Be Thou my [G]Wisdom, and [D]Thou my true [G]Word;
[G]I ever [A]with Thee and [Bm]Thou with me, [A]Lord;
[G]Thou my great [D]Father, [G]I Thy true [D]son;
[Bm]Thou in me [G]dwelling, and [A]I with Thee [D]one.

{Verse 3}
[D]Riches I [G]heed not, nor [D]man's empty [G]praise,
[G]Thou mine in[A]heritance, [Bm]now and al[A]ways:
[G]Thou and Thou [D]only, [G]first in my [D]heart,
[Bm]High King of [G]Heaven, my [A]Treasure Thou [D]art.

{Verse 4}
[D]High King of [G]Heaven, my [D]victory [G]won,
[G]May I reach [A]Heaven's joys, [Bm]O bright Heaven's [A]Sun!
[G]Heart of my [D]own heart, [G]whatever be[D]fall,
[Bm]Still be my [G]Vision, O [A]Ruler of [D]all.$s$, 'Public domain', 10),
($s$rock-of-ages$s$, $s$Rock of Ages$s$, $s$Augustus M. Toplady, 1776 · music: Toplady, Thomas Hastings$s$, 'Bb', 72, '4/4', array['hymn', 'classic', 'communion']::text[], $s${Verse 1}
[Bb]Rock of Ages, [F7]cleft for [Bb]me,
Let me hide my[Eb]self in [Bb]Thee;
[F]Let the water [F7]and the [Bb]blood,
[F]From Thy wounded [C7]side which [F]flowed,
[Bb]Be of sin the [Eb]double [Bb]cure;
Save from wrath and [F7]make me [Bb]pure.

{Verse 2}
[Bb]Not the labors [F7]of my [Bb]hands
Can fulfil Thy [Eb]law's de[Bb]mands;
[F]Could my zeal no [F7]respite [Bb]know,
[F]Could my tears for[C7]ever [F]flow,
[Bb]All for sin could [Eb]not a[Bb]tone;
Thou must save, and [F7]Thou a[Bb]lone.

{Verse 3}
[Bb]Nothing in my [F7]hand I [Bb]bring,
Simply to Thy [Eb]cross I [Bb]cling;
[F]Naked, come to [F7]Thee for [Bb]dress;
[F]Helpless, look to [C7]Thee for [F]grace;
[Bb]Foul, I to the [Eb]fountain [Bb]fly;
Wash me, Savior, [F7]or I [Bb]die.

{Verse 4}
[Bb]While I draw this [F7]fleeting [Bb]breath,
When mine eyes shall [Eb]close in [Bb]death,
[F]When I soar to [F7]worlds un[Bb]known,
[F]See Thee on Thy [C7]judgment [F]throne,
[Bb]Rock of Ages, [Eb]cleft for [Bb]me,
Let me hide my[F7]self in [Bb]Thee.$s$, 'Public domain', 11),
($s$joyful-joyful-we-adore-thee$s$, $s$Joyful, Joyful, We Adore Thee$s$, $s$Henry van Dyke, 1907 · music: Ode to Joy, Ludwig van Beethoven$s$, 'G', 104, '4/4', array['hymn', 'praise', 'classic']::text[], $s${Verse 1}
[G]Joyful, joyful, [D]we a[G]dore Thee,
[C]God of [G]glory, [D]Lord of [G]love;
[G]Hearts unfold like [D]flowers be[G]fore Thee,
[C]Opening [G]to the [D]sun a[G]bove.
[D]Melt the clouds of [G]sin and [D]sadness;
[D]Drive the [G]dark of [Em]doubt a[A]way;
[G]Giver of im[D]mortal [G]gladness,
[C]Fill us [G]with the [D]light of [G]day!

{Verse 2}
[G]All Thy works with [D]joy sur[G]round Thee,
[C]Earth and [G]heaven re[D]flect Thy [G]rays,
[G]Stars and angels [D]sing a[G]round Thee,
[C]Center [G]of un[D]broken [G]praise.
[D]Field and forest, [G]vale and [D]mountain,
[D]Flowery [G]meadow, [Em]flashing [A]sea,
[G]Singing bird and [D]flowing [G]fountain
[C]Call us [G]to re[D]joice in [G]Thee.

{Verse 3}
[G]Mortals, join the [D]happy [G]chorus,
[C]Which the [G]morning [D]stars be[G]gan;
[G]Father love is [D]reigning [G]o'er us,
[C]Brother [G]love binds [D]man to [G]man.
[D]Ever singing, [G]march we [D]onward,
[D]Victors [G]in the [Em]midst of [A]strife,
[G]Joyful music [D]leads us [G]sunward
[C]In the [G]triumph [D]song of [G]life.$s$, 'Public domain', 12),
($s$to-god-be-the-glory$s$, $s$To God Be the Glory$s$, $s$Fanny J. Crosby, 1875 · music: William H. Doane$s$, 'G', 108, '4/4', array['hymn', 'praise', 'classic']::text[], $s${Verse 1}
To [G]God be the glory, great [C]things He hath [G]done;
So loved He the world that He [A7]gave us His [D]Son,
Who [G]yielded His life an a[C]tonement for [G]sin,
And opened the [D]life gate that [D7]all may go [G]in.

{Refrain}
Praise the [D]Lord, praise the Lord, let the [G]earth hear His voice!
Praise the [D]Lord, praise the Lord, let the [G]people re[D]joice!
O come to the [G]Father, through [C]Jesus the [G]Son,
And give Him the [D]glory, great [D7]things He hath [G]done.

{Verse 2}
O [G]perfect redemption, the [C]purchase of [G]blood,
To every believer the [A7]promise of [D]God;
The [G]vilest offender who [C]truly be[G]lieves,
That moment from [D]Jesus a [D7]pardon re[G]ceives.

{Verse 3}
Great [G]things He hath taught us, great [C]things He hath [G]done,
And great our rejoicing through [A7]Jesus the [D]Son;
But [G]purer, and higher, and [C]greater will [G]be
Our wonder, our [D]transport, when [D7]Jesus we [G]see.$s$, 'Public domain', 13),
($s$i-surrender-all$s$, $s$I Surrender All$s$, $s$Judson W. Van DeVenter, 1896 · music: Winfield S. Weeden$s$, 'D', 80, '4/4', array['hymn', 'worship', 'classic']::text[], $s${Verse 1}
[D]All to Jesus [G]I sur[D]render;
All to Him I [E7]freely [A]give;
[D]I will ever [G]love and [D]trust Him,
In His presence [A7]daily [D]live.

{Refrain}
[D]I sur[A]render [D]all,
[D]I sur[G]render [D]all;
[D]All to Thee, my [G]blessed [D]Savior,
I sur[A7]render [D]all.

{Verse 2}
[D]All to Jesus [G]I sur[D]render;
Humbly at His [E7]feet I [A]bow,
[D]Worldly pleasures [G]all for[D]saken;
Take me, Jesus, [A7]take me [D]now.

{Verse 3}
[D]All to Jesus [G]I sur[D]render;
Make me, Savior, [E7]wholly [A]Thine;
[D]Let me feel the [G]Holy [D]Spirit,
Truly know that [A7]Thou art [D]mine.

{Verse 4}
[D]All to Jesus [G]I sur[D]render;
Lord, I give my[E7]self to [A]Thee;
[D]Fill me with Thy [G]love and [D]power;
Let Thy blessing [A7]fall on [D]me.$s$, 'Public domain', 14),
($s$leaning-on-the-everlasting-arms$s$, $s$Leaning on the Everlasting Arms$s$, $s$Elisha A. Hoffman, 1887 · music: Anthony J. Showalter$s$, 'G', 100, '4/4', array['hymn', 'classic']::text[], $s${Verse 1}
What a [G]fellowship, what a [C]joy di[G]vine,
Leaning on the ever[A7]lasting [D]arms;
What a [G]blessedness, what a [C]peace is [G]mine,
Leaning [D]on the ever[D7]lasting [G]arms.

{Refrain}
[G]Leaning, [C]leaning,
[G]Safe and secure from [A7]all a[D]larms;
[G]Leaning, [C]leaning,
[G]Leaning on the [D]ever[D7]lasting [G]arms.

{Verse 2}
O how [G]sweet to walk in this [C]pilgrim [G]way,
Leaning on the ever[A7]lasting [D]arms;
O how [G]bright the path grows from [C]day to [G]day,
Leaning [D]on the ever[D7]lasting [G]arms.

{Verse 3}
What have [G]I to dread, what have [C]I to [G]fear,
Leaning on the ever[A7]lasting [D]arms?
I have [G]blessed peace with my [C]Lord so [G]near,
Leaning [D]on the ever[D7]lasting [G]arms.$s$, 'Public domain', 15),
($s$nothing-but-the-blood$s$, $s$Nothing but the Blood$s$, $s$Robert Lowry, 1876$s$, 'G', 92, '4/4', array['hymn', 'communion', 'classic']::text[], $s${Verse 1}
What can [G]wash away my sin?
Nothing but the [D]blood of [G]Jesus;
What can [G]make me whole again?
Nothing but the [D]blood of [G]Jesus.

{Refrain}
O! [C]precious is the [G]flow
That makes me white as [D]snow;
No [G]other fount I [C]know,
Nothing but the [D]blood of [G]Jesus.

{Verse 2}
For my [G]pardon this I see,
Nothing but the [D]blood of [G]Jesus;
For my [G]cleansing this my plea,
Nothing but the [D]blood of [G]Jesus.

{Verse 3}
Nothing [G]can for sin atone,
Nothing but the [D]blood of [G]Jesus;
Naught of [G]good that I have done,
Nothing but the [D]blood of [G]Jesus.

{Verse 4}
This is [G]all my hope and peace,
Nothing but the [D]blood of [G]Jesus;
This is [G]all my righteousness,
Nothing but the [D]blood of [G]Jesus.$s$, 'Public domain', 16),
($s$count-your-blessings$s$, $s$Count Your Blessings$s$, $s$Johnson Oatman Jr., 1897 · music: Edwin O. Excell$s$, 'D', 104, '4/4', array['hymn', 'kids', 'classic']::text[], $s${Verse 1}
When upon life's [D]billows you are tempest-tossed,
When you are dis[A]couraged, thinking all is [D]lost,
Count your many [D]blessings, name them one by [G]one,
And it will sur[D]prise you what the [A7]Lord hath [D]done.

{Refrain}
Count your [D]blessings, name them one by one;
Count your [A]blessings, see what God hath [D]done!
Count your [D]blessings, name them one by [G]one;
Count your many [D]blessings, see what [A7]God hath [D]done.

{Verse 2}
Are you ever [D]burdened with a load of care?
Does the cross seem [A]heavy you are called to [D]bear?
Count your many [D]blessings, every doubt will [G]fly,
And you will be [D]singing as the [A7]days go [D]by.

{Verse 3}
So, amid the [D]conflict whether great or small,
Do not be dis[A]couraged, God is over [D]all;
Count your many [D]blessings, angels will at[G]tend,
Help and comfort [D]give you to your [A7]journey's [D]end.$s$, 'Public domain', 17),
($s$standing-on-the-promises$s$, $s$Standing on the Promises$s$, $s$R. Kelso Carter, 1886$s$, 'Bb', 112, '6/8', array['hymn', 'praise', 'classic']::text[], $s${Verse 1}
[Bb]Standing on the promises of [Eb]Christ my [Bb]King,
Through eternal ages let His [C7]praises [F]ring;
[Bb]Glory in the highest, I will [Eb]shout and [Bb]sing,
Standing on the [F]promises of [F7]God. [Bb]

{Refrain}
[Bb]Standing, [Eb]standing,
[F]Standing on the promises of [Bb]God my Savior;
[Bb]Standing, [Eb]standing,
I'm [Bb]standing on the [F]promises of [F7]God. [Bb]

{Verse 2}
[Bb]Standing on the promises that [Eb]cannot [Bb]fail,
When the howling storms of doubt and [C7]fear as[F]sail,
[Bb]By the living Word of God I [Eb]shall pre[Bb]vail,
Standing on the [F]promises of [F7]God. [Bb]

{Verse 3}
[Bb]Standing on the promises I [Eb]now can [Bb]see
Perfect, present cleansing in the [C7]blood for [F]me;
[Bb]Standing in the liberty where [Eb]Christ makes [Bb]free,
Standing on the [F]promises of [F7]God. [Bb]$s$, 'Public domain', 18),
($s$crown-him-with-many-crowns$s$, $s$Crown Him with Many Crowns$s$, $s$Matthew Bridges, 1851 & Godfrey Thring, 1874 · music: Diademata, George J. Elvey$s$, 'D', 96, '4/4', array['hymn', 'praise', 'classic']::text[], $s${Verse 1}
[D]Crown Him with [A]many [D]crowns,
The [G]Lamb up[D]on His [A]throne;
[D]Hark! how the [A]heavenly [Bm]anthem [F#m]drowns
All [Bm]music [E7]but its [A]own.
A[D]wake, my [G]soul, and [D]sing
Of [G]Him who [D]died for [A]thee,
And [D]hail Him [G]as thy [D]matchless [Bm]King
Through [G]all e[A7]terni[D]ty.

{Verse 2}
[D]Crown Him the [A]Lord of [D]life,
Who [G]triumphed [D]o'er the [A]grave,
[D]And rose vic[A]torious [Bm]in the [F#m]strife
For [Bm]those He [E7]came to [A]save;
His [D]glories [G]now we [D]sing,
Who [G]died, and [D]rose on [A]high,
Who [D]died e[G]ternal [D]life to [Bm]bring,
And [G]lives that [A7]death may [D]die.

{Verse 3}
[D]Crown Him the [A]Lord of [D]heaven,
En[G]throned in [D]worlds a[A]bove;
[D]Crown Him the [A]King to [Bm]whom is [F#m]given
The [Bm]wondrous [E7]name of [A]Love.
Crown [D]Him with [G]many [D]crowns,
As [G]thrones be[D]fore Him [A]fall;
Crown [D]Him, ye [G]kings, with [D]many [Bm]crowns,
For [G]He is [A7]King of [D]all.$s$, 'Public domain', 19),
($s$o-for-a-thousand-tongues$s$, $s$O for a Thousand Tongues to Sing$s$, $s$Charles Wesley, 1739 · music: Azmon, Carl G. Gläser$s$, 'G', 92, '3/4', array['hymn', 'praise', 'classic']::text[], $s${Verse 1}
O [G]for a thousand [D]tongues to [G]sing
My [C]great Re[G]deemer's [D]praise,
The [G]glories of my [C]God and [G]King,
The [D]triumphs [D7]of His [G]grace!

{Verse 2}
My [G]gracious Master [D]and my [G]God,
As[C]sist me [G]to pro[D]claim,
To [G]spread through all the [C]earth a[G]broad
The [D]honors [D7]of Thy [G]name.

{Verse 3}
Jesus! [G]the name that [D]charms our [G]fears,
That [C]bids our [G]sorrows [D]cease;
'Tis [G]music in the [C]sinner's [G]ears,
'Tis [D]life, and [D7]health, and [G]peace.

{Verse 4}
He [G]breaks the power of [D]canceled [G]sin,
He [C]sets the [G]prisoner [D]free;
His [G]blood can make the [C]foulest [G]clean;
His [D]blood a[D7]vailed for [G]me.$s$, 'Public domain', 20),
($s$all-hail-the-power$s$, $s$All Hail the Power of Jesus' Name$s$, $s$Edward Perronet, 1779 · music: Coronation, Oliver Holden$s$, 'G', 96, '4/4', array['hymn', 'praise', 'classic']::text[], $s${Verse 1}
All [G]hail the power of [C]Jesus' [G]name!
Let [D]angels prostrate [G]fall;
Bring [G]forth the royal [C]di[G]adem,
And [C]crown [G]Him, [D]crown [G]Him,
[C]Crown [G]Him, and [D]crown Him Lord of [G]all.

{Verse 2}
Ye [G]chosen seed of [C]Israel's [G]race,
Ye [D]ransomed from the [G]fall,
Hail [G]Him who saves you [C]by His [G]grace,
And [C]crown [G]Him, [D]crown [G]Him,
[C]Crown [G]Him, and [D]crown Him Lord of [G]all.

{Verse 3}
Let [G]every kindred, [C]every [G]tribe,
On [D]this terrestrial [G]ball,
To [G]Him all majes[C]ty a[G]scribe,
And [C]crown [G]Him, [D]crown [G]Him,
[C]Crown [G]Him, and [D]crown Him Lord of [G]all.

{Verse 4}
O [G]that with yonder [C]sacred [G]throng
We [D]at His feet may [G]fall!
We'll [G]join the ever[C]lasting [G]song,
And [C]crown [G]Him, [D]crown [G]Him,
[C]Crown [G]Him, and [D]crown Him Lord of [G]all.$s$, 'Public domain', 21),
($s$there-is-power-in-the-blood$s$, $s$There Is Power in the Blood$s$, $s$Lewis E. Jones, 1899$s$, 'Bb', 104, '4/4', array['hymn', 'communion', 'classic']::text[], $s${Verse 1}
Would you [Bb]be free from the burden of sin?
There's power in the [F]blood, power in the [Bb]blood;
Would you [Bb]o'er evil a [Eb]victory [Bb]win?
There's wonderful [F]power in the [Bb]blood.

{Refrain}
There is [Bb]power, power, [Eb]wonder-working [Bb]power
In the blood of the [F]Lamb;
There is [Bb]power, power, [Eb]wonder-working [Bb]power
In the precious [F]blood of the [Bb]Lamb.

{Verse 2}
Would you [Bb]be free from your passion and pride?
There's power in the [F]blood, power in the [Bb]blood;
Come for a [Bb]cleansing to [Eb]Calvary's [Bb]tide;
There's wonderful [F]power in the [Bb]blood.

{Verse 3}
Would you [Bb]be whiter, much whiter than snow?
There's power in the [F]blood, power in the [Bb]blood;
Sin stains are [Bb]lost in its [Eb]life-giving [Bb]flow;
There's wonderful [F]power in the [Bb]blood.

{Verse 4}
Would you [Bb]do service for Jesus your King?
There's power in the [F]blood, power in the [Bb]blood;
Would you live [Bb]daily His [Eb]praises to [Bb]sing?
There's wonderful [F]power in the [Bb]blood.$s$, 'Public domain', 22),
($s$silent-night$s$, $s$Silent Night$s$, $s$Joseph Mohr, 1818, tr. John F. Young, 1859 · music: Franz X. Gruber$s$, 'Bb', 60, '6/8', array['christmas', 'hymn', 'classic']::text[], $s${Verse 1}
[Bb]Silent night, holy night,
[F7]All is calm, [Bb]all is bright
[Eb]Round yon virgin [Bb]mother and child.
[Eb]Holy infant so [Bb]tender and mild,
[F7]Sleep in heavenly [Bb]peace,
[Bb]Sleep in [F7]heavenly [Bb]peace.

{Verse 2}
[Bb]Silent night, holy night,
[F7]Shepherds quake [Bb]at the sight;
[Eb]Glories stream from [Bb]heaven afar,
[Eb]Heavenly hosts sing [Bb]Alleluia!
[F7]Christ, the Savior, is [Bb]born,
[Bb]Christ, the [F7]Savior, is [Bb]born!

{Verse 3}
[Bb]Silent night, holy night,
[F7]Son of God, [Bb]love's pure light;
[Eb]Radiant beams from [Bb]Thy holy face
[Eb]With the dawn of re[Bb]deeming grace,
[F7]Jesus, Lord, at Thy [Bb]birth,
[Bb]Jesus, [F7]Lord, at Thy [Bb]birth.$s$, 'Public domain', 23),
($s$joy-to-the-world$s$, $s$Joy to the World$s$, $s$Isaac Watts, 1719 · music: Antioch, arr. Lowell Mason$s$, 'D', 104, '2/4', array['christmas', 'praise', 'hymn']::text[], $s${Verse 1}
[D]Joy to the [G]world! [A7]the Lord is [D]come;
Let earth re[A]ceive her [D]King;
Let every heart pre[G]pare Him room,
And heaven and nature [D]sing,
And heaven and nature [A]sing,
And [D]heaven, and [G]heaven, and [D]na[A7]ture [D]sing.

{Verse 2}
[D]Joy to the [G]earth! [A7]the Savior [D]reigns;
Let men their [A]songs em[D]ploy;
While fields and floods, rocks, [G]hills, and plains
Repeat the sounding [D]joy,
Repeat the sounding [A]joy,
Re[D]peat, re[G]peat the [D]sound[A7]ing [D]joy.

{Verse 3}
[D]He rules the [G]world [A7]with truth and [D]grace,
And makes the [A]nations [D]prove
The glories of His [G]righteousness,
And wonders of His [D]love,
And wonders of His [A]love,
And [D]wonders, [G]wonders, [D]of [A7]His [D]love.$s$, 'Public domain', 24),
($s$tis-so-sweet-to-trust-in-jesus$s$, $s$'Tis So Sweet to Trust in Jesus$s$, $s$Louisa M. R. Stead, 1882 · music: William J. Kirkpatrick$s$, 'G', 92, '4/4', array['hymn', 'prayer', 'classic']::text[], $s${Verse 1}
'Tis so [G]sweet to trust in Jesus,
Just to take Him [D]at His word;
Just to [G]rest upon His [C]promise;
Just to [G]know, "Thus [D]saith the [G]Lord."

{Refrain}
[G]Jesus, Jesus, how I [C]trust Him!
[G]How I've proved Him [D]o'er and o'er!
[G]Jesus, Jesus, precious [C]Jesus!
O for [G]grace to [D]trust Him [G]more!

{Verse 2}
O how [G]sweet to trust in Jesus,
Just to trust His [D]cleansing blood;
Just in [G]simple faith to [C]plunge me
'Neath the [G]healing, [D]cleansing [G]flood!

{Verse 3}
I'm so [G]glad I learned to trust Thee,
Precious Jesus, [D]Savior, Friend;
And I [G]know that Thou art [C]with me,
Wilt be [G]with me [D]to the [G]end.$s$, 'Public domain', 25),
($s$i-need-thee-every-hour$s$, $s$I Need Thee Every Hour$s$, $s$Annie S. Hawks, 1872 · music: Robert Lowry$s$, 'G', 76, '3/4', array['hymn', 'prayer', 'classic']::text[], $s${Verse 1}
I [G]need Thee every [D]hour, most [G]gracious Lord;
No [C]tender voice like [G]Thine can [A7]peace af[D]ford.

{Refrain}
I [G]need Thee, O I [C]need Thee;
Every [G]hour I [D]need Thee!
O [G]bless me now, my [C]Savior,
I [G]come to [D7]Thee! [G]

{Verse 2}
I [G]need Thee every [D]hour, stay [G]Thou nearby;
Temp[C]tations lose their [G]power when [A7]Thou art [D]nigh.

{Verse 3}
I [G]need Thee every [D]hour, in [G]joy or pain;
Come [C]quickly and a[G]bide, or [A7]life is [D]vain.

{Verse 4}
I [G]need Thee every [D]hour, most [G]Holy One;
O [C]make me Thine in[G]deed, Thou [A7]blessed [D]Son.$s$, 'Public domain', 26),
($s$when-we-all-get-to-heaven$s$, $s$When We All Get to Heaven$s$, $s$Eliza E. Hewitt, 1898 · music: Emily D. Wilson$s$, 'Ab', 108, '4/4', array['hymn', 'praise', 'classic']::text[], $s${Verse 1}
Sing the [Ab]wondrous love of Jesus,
Sing His mercy [Eb]and His grace;
In the [Ab]mansions bright and [Db]blessed
He'll pre[Ab]pare for [Eb7]us a [Ab]place.

{Refrain}
When we [Ab]all get to heaven,
What a day of rejoicing that will [Eb]be!
When we [Ab]all see [Db]Jesus,
We'll sing and [Ab]shout the [Eb7]victo[Ab]ry!

{Verse 2}
While we [Ab]walk the pilgrim pathway,
Clouds will overspread [Eb]the sky;
But when [Ab]traveling days are [Db]over,
Not a [Ab]shadow, [Eb7]not a [Ab]sigh.

{Verse 3}
Let us [Ab]then be true and faithful,
Trusting, serving [Eb]every day;
Just one [Ab]glimpse of Him in [Db]glory
Will the [Ab]toils of [Eb7]life re[Ab]pay.$s$, 'Public domain', 27),
($s$softly-and-tenderly$s$, $s$Softly and Tenderly Jesus Is Calling$s$, $s$Will L. Thompson, 1880$s$, 'G', 72, '6/8', array['hymn', 'classic']::text[], $s${Verse 1}
[G]Softly and tenderly [C]Jesus is [G]calling,
Calling for you and for [D]me;
[G]See, on the portals He's [C]waiting and [G]watching,
Watching for [D]you and for [G]me.

{Refrain}
[D]Come home, [G]come home,
[D]You who are weary, come [G]home;
[G]Earnestly, tenderly, [C]Jesus is [G]calling,
Calling, O [D]sinner, come [G]home!

{Verse 2}
[G]Why should we tarry when [C]Jesus is [G]pleading,
Pleading for you and for [D]me?
[G]Why should we linger and [C]heed not His [G]mercies,
Mercies for [D]you and for [G]me?

{Verse 3}
[G]O for the wonderful [C]love He has [G]promised,
Promised for you and for [D]me!
[G]Though we have sinned, He has [C]mercy and [G]pardon,
Pardon for [D]you and for [G]me.$s$, 'Public domain', 28)
on conflict (slug) do nothing;

-- ===== seed.sql
-- =====================================================================
-- AGAPE — starter content (optional, safe to run once after the migrations)
-- Only real Bible content: a trivia pack and a Verse Match pack so the
-- games work on day one. Everything else (sermons, courses, groups,
-- events…) is added by staff in /admin.
-- =====================================================================

with p as (insert into public.question_packs (title, game, published) values ('Bible basics', 'trivia', true) returning id)
insert into public.questions (pack_id, prompt, options, answer, reference)
select p.id, q.prompt, q.options::jsonb, q.answer::jsonb, q.ref from p, (values
  ('Who built the ark?', '["Moses","Noah","Abraham","David"]', '1', 'Genesis 6'),
  ('How many books are in the Bible?', '["39","27","66","73"]', '2', null),
  ('Which disciple walked on water with Jesus?', '["John","Peter","Thomas","Andrew"]', '1', 'Matthew 14:29'),
  ('What was Paul''s name before his conversion?', '["Silas","Saul","Stephen","Simon"]', '1', 'Acts 13:9'),
  ('Where was Jesus born?', '["Nazareth","Jerusalem","Bethlehem","Capernaum"]', '2', 'Luke 2:4–7'),
  ('Who was swallowed by a great fish?', '["Jonah","Elijah","Daniel","Job"]', '0', 'Jonah 1:17'),
  ('Who led the Israelites out of Egypt?', '["Joshua","Moses","Aaron","Samuel"]', '1', 'Exodus 12'),
  ('What is the first book of the New Testament?', '["Mark","Acts","Matthew","John"]', '2', null)
) as q(prompt, options, answer, ref);

-- Verse Match: "___" marks each blank; answer = the missing words in order; options = extra wrong words.
with p as (insert into public.question_packs (title, game, published) values ('Memory verses', 'verse_match', true) returning id)
insert into public.questions (pack_id, prompt, options, answer, reference)
select p.id, q.prompt, q.options::jsonb, q.answer::jsonb, q.ref from p, (values
  ('For God so loved the ___ that he gave his one and only ___.', '["law","heart","nations"]', '["world","Son"]', 'John 3:16'),
  ('The Lord is my ___; I shall not ___.', '["king","fear","rock"]', '["shepherd","want"]', 'Psalm 23:1'),
  ('Your word is a ___ to my feet and a ___ to my path.', '["song","sword","shield"]', '["lamp","light"]', 'Psalm 119:105'),
  ('Be still, and ___ that I am ___.', '["pray","King","wait"]', '["know","God"]', 'Psalm 46:10'),
  ('I can do all things through ___ who ___ me.', '["faith","loves","angels"]', '["Christ","strengthens"]', 'Philippians 4:13')
) as q(prompt, options, answer, ref);

-- ---------------------------------------------------------------------
-- Make yourself the first admin (after signing up in the app or /admin):
--   update public.profiles set role = 'admin' where email = 'you@example.com';
-- From then on, change roles in /admin → Members & roles.
-- ---------------------------------------------------------------------
